_root:
  # default params
  CLUSTER_IP: "10.11.1.251"
  DNS_IP: "10.11.1.254"
  REPLICAS_NUM: 1
  # TODO: investigate and remove
  CUDA_VERSION: "9.0"
  DOCKER_REGISTRY: "kubeadm.ipavlov.mipt.ru:5000"
  COMMIT: ""
  PORT: 5000
  serialize_config: false
  image_polling_timeout_sec: 300
  deployment_polling_timeout_sec: 600

  # composed params
  LOG_FILE: "{{FULL_MODEL_NAME}}.log"
  RUN_FILE: "run_{{MODEL_NAME}}.sh"
  KUBER_DP_FILE: "{{FULL_MODEL_NAME}}_dp.yaml"
  KUBER_LB_FILE: "{{FULL_MODEL_NAME}}_lb.yaml"
  KUBER_DP_NAME: "{{FULL_MODEL_NAME_DASHED}}-dp"
  KUBER_LB_NAME: "{{FULL_MODEL_NAME_DASHED}}-lb"
  KUBER_IMAGE_TAG: "{{DOCKER_REGISTRY}}/{{PREFIX}}/{{MODEL_NAME}}"
  KUBER_CONTAINER_PORT_NAME: "cp{{PORT}}"

  # script generated params
  FULL_MODEL_NAME: ""
  PREFIX: ""
  MODEL_NAME: ""
  RUN_CMD: ""
  FULL_MODEL_NAME_DASHED: ""

  # human set params
  TF_VERSION: ""
  CLUSTER_PORT: ""
  MODEL_ARGS: []
  run_mode: ""
  run_params: {}
  run_flags: []
  test_image_url: ""
  test_deployment_url: ""
  pipeline: ""


# examples for some params
_docs:
  run_flags: ["--default-skill"]
  run_params:
    --host: 10.11.1.58
    --port: 8433
    --token: 343f5688-4df9-4ef1-a05e-cfd9af9114aa


dp:
  # default params
  run_mode: "riseapi"
  pipeline: "all_up_kuber_no_tests"
  BASE_IMAGE: "deeppavlov/base-cpu:0.5.1"
  GPU_UNITS_NUM: 0

  # composed params
  test_image_url: "http://0.0.0.0:{{PORT}}/answer/poller"
  test_deployment_url: "https://{{CLUSTER_PORT}}.lnsigo.mipt.ru/answer/poller"

  # human set params
  CONFIG: ""
  CLUSTER_PORT: ""


agent_transport:
  # default params
  pipeline: "all_up_kuber_no_tests"
  INSTANCE_ID: ""

  AGENT_NAMESPACE: "deeppavlov_agent"
  AGENT_NAME: "dp_agent"
  AGENT_REPSONSE_TIMEOUT: 20

  SERVICE_NAME: "service"
  BATCH_SIZE: 5
  SERVICE_INFER_TIMEOUT: 30
  SERVICE_FORMATTER: "formatter"
  SERVICE_CALLER: "default"
  SERVICE_URL: "http://localhost:5000/service"

  TRANSPORT_TYPE: "rabbitmq"
  RABBIT_LOGIN: "guest"
  RABBIT_PASSWORD: "guest"
  RABBIT_VIRTUALHOST: "/"

  # composed params
  MONGO_HOST: "{{CLUSTER_IP}}"
  RABBIT_HOST: "{{CLUSTER_IP}}"

  # human set params
  MODE: ""
  CONFIG: ""
  CLUSTER_PORT: ""
  MONGO_PORT: ""
  RABBIT_PORT: ""


agent_obsolete:
  # default params
  pipeline: "make_files_and_kuber_no_tests"

  # human set params
  CONFIG: ""
  CLUSTER_PORT: ""


router_bot:
  # default params
  MONGO_DOCKER_TAG: "4.0.6-xenial"
  MONGO_PROTOCOL: "mongodb"
  MONGO_HOST: "127.0.0.1"
  MONGO_PORT: 27017
  pipeline: "make_files_and_kuber_no_tests"

  # composed params
  KUBER_IMAGE_TAG: "{{DOCKER_REGISTRY}}/stand/router_bot"
  MONGO_KUBER_IMAGE_TAG: "{{DOCKER_REGISTRY}}/stand/db/mongo:{{MONGO_DOCKER_TAG}}"
  FB_WEBHOOK: "https://{{CLUSTER_PORT}}.lnsigo.mipt.ru/fb"
  TG_WEBHOOK: "https://{{CLUSTER_PORT}}.lnsigo.mipt.ru/tg"

  # human set params
  CLUSTER_PORT: ""
  CLUSTER_MONGO_PORT: ""
  CLUSTER_SSH_PORT: ""
  FB_PAGE_ACCESS_TOKEN: ""
  FB_WEBHOOK_SECRET: ""
  TG_TOKEN: ""
  PROXY_PROTOCOL: ""
  PROXY_HOST: ""
  PROXY_PORT: ""
  PROXY_USER: ""
  PROXY_PASS: ""


rabbitmq:
  # default params
  RABBIT_DOCKER_TAG: "3-management"
  pipeline: "make_files_and_kuber_no_tests"

  # human set params
  CLUSTER_PORT: ""
  CLUSTER_MANAGEMENT_PORT: ""


mongo_db:
  # default params
  MONGO_DOCKER_TAG: "4.0.6-xenial"
  PORT: 27017
  pipeline: "make_files_and_kuber_no_tests"

  # composed params
  KUBER_IMAGE_TAG: "{{DOCKER_REGISTRY}}/stand/db/mongo:{{MONGO_DOCKER_TAG}}"

  # human set params
  CLUSTER_PORT: ""


http_proxy:
  # default params
  pipeline: "make_files_and_kuber_no_tests"

  # composed params
  KUBER_IMAGE_TAG: "{{DOCKER_REGISTRY}}/stand/http_proxy"
  PORT: "{{CLUSTER_PORT}}"

  # human set params
  CLUSTER_PORT: ""
  PROXYED_HOST: ""
  PROXYED_PORT: ""