_root:
  # default params
  NODE_LIST: [gpu1, gpu9]
  CLUSTER_IP: "10.11.1.251"
  DNS_IP: "10.11.1.254"
  REPLICAS_NUM: 1
  GPU_UNITS_NUM: 0
  CUDA_VISIBLE_DEVICES: ""
  DOCKER_REGISTRY: "kubeadm.ipavlov.mipt.ru:5000"
  COMMIT: ""
  PORT: 5000
  serialize_config: false
  image_polling_timeout_sec: 300
  deployment_polling_timeout_sec: 600

  # composed params
  LOG_FILE: "{{FULL_MODEL_NAME}}.log"
  KUBER_DP_FILE: "{{FULL_MODEL_NAME}}_dp.yaml"
  KUBER_LB_FILE: "{{FULL_MODEL_NAME}}_lb.yaml"
  KUBER_DP_NAME: "{{FULL_MODEL_NAME_DASHED}}-dp"
  KUBER_LB_NAME: "{{FULL_MODEL_NAME_DASHED}}-lb"
  KUBER_IMAGE_TAG: "{{DOCKER_REGISTRY}}/{{FULL_MODEL_NAME}}"

  # script generated params
  FULL_MODEL_NAME: ""
  RUN_CMD: ""
  FULL_MODEL_NAME_DASHED: ""

  # human set params
  TF_VERSION: ""
  CLUSTER_PORT: ""
  MODEL_ARGS: []
  run_mode: ""
  run_params: {}
  run_flags: []
  test_image_url: ""
  test_deployment_url: ""
  pipeline: ""


# examples for some params
_docs:
  MODEL_ARGS: ["arg_name"]
  run_flags: ["--default-skill"]
  run_params:
    --host: 10.11.1.58
    --port: 8433
    --token: 343f5688-4df9-4ef1-a05e-cfd9af9114aa


dp_base_cpu:
  # default params
  # TODO: think about testing this template
  pipeline: "make_files_and_docker_no_tests"
  DOCKER_REGISTRY: "deeppavlov"

  # composed params
  KUBER_IMAGE_TAG: "{{DOCKER_REGISTRY}}/base-cpu:{{IMAGE_VERSION}}"

  # human set params
  IMAGE_VERSION: ""
  PYTHON_BASE_IMAGE: ""
  COMMIT: ""


dp_stand:
  # default params
  run_mode: "riseapi"
  pipeline: "all_up_kuber_no_tests"
  BASE_IMAGE: "deeppavlov/base-cpu:0.7.1"

  # composed params
  test_image_url: "http://0.0.0.0:{{PORT}}/probe"
  test_deployment_url: "https://{{CLUSTER_PORT}}.lnsigo.mipt.ru/probe"

  # human set params
  CONFIG: ""
  CLUSTER_PORT: ""


agent_agent:
  # default_params:
  pipeline: "all_up_kuber_no_tests"

  # human set params
  COMMIT: ""


agent_service:
  # default_params:
  pipeline: "all_up_kuber_no_tests"
  BASE_IMAGE: "deeppavlov/base-cpu:0.7.1"

  # human set params
  DP_COMMIT: ""
  DPA_COMMIT: ""
  CONFIG: ""


agent_custom_service:
  # default_params:
  pipeline: "all_up_kuber_no_tests"

  # human set params
  BASE_IMAGE: ""
  DPA_COMMIT: ""
  CONFIG: ""


socialbot_service:
  # default_params:
  pipeline: "all_up_kuber_no_tests"
  SECRET_NAME: "dream-secret"
  # human set params
  BASE_IMAGE: ""


router_bot:
  # default params
  pipeline: "make_files_and_kuber_no_tests"
  MONGO_DOCKER_TAG: "4.0.6-xenial"
  MONGO_PROTOCOL: "mongodb"
  MONGO_HOST: "127.0.0.1"
  MONGO_PORT: 27017

  # composed params
  KUBER_IMAGE_TAG: "{{DOCKER_REGISTRY}}/stand/router_bot"
  MONGO_KUBER_IMAGE_TAG: "{{DOCKER_REGISTRY}}/stand/db/mongo:{{MONGO_DOCKER_TAG}}"
  FB_WEBHOOK: "https://{{CLUSTER_PORT}}.lnsigo.mipt.ru/fb"
  TG_WEBHOOK: "https://{{CLUSTER_PORT}}.lnsigo.mipt.ru/tg"

  # human set params
  CLUSTER_PORT: ""
  CLUSTER_MONGO_PORT: ""
  CLUSTER_SSH_PORT: ""
  FB_PAGE_ACCESS_TOKEN: ""
  FB_WEBHOOK_SECRET: ""
  TG_TOKEN: ""
  PROXY_PROTOCOL: ""
  PROXY_HOST: ""
  PROXY_PORT: ""
  PROXY_USER: ""
  PROXY_PASS: ""


router_bot_poller:
  # default params
  pipeline: "make_files_and_kuber_no_tests"

  # composed params
  KUBER_IMAGE_TAG: "{{DOCKER_REGISTRY}}/stand/router_bot_poller"

  # human set params
  run_flags: ["--agent", "--state", "--convai"]
  run_params:
    --model_url: ""
    --host: ""
    --port: ""
    --token: ""


rabbitmq:
  # default params
  RABBIT_DOCKER_TAG: "3-management"
  pipeline: "make_files_and_kuber_no_tests"

  # human set params
  CLUSTER_PORT: ""
  CLUSTER_MANAGEMENT_PORT: ""


mongo_db:
  # default params
  MONGO_DOCKER_TAG: "4.0.6-xenial"
  PORT: 27017
  pipeline: "make_files_and_kuber_no_tests"

  # composed params
  KUBER_IMAGE_TAG: "{{DOCKER_REGISTRY}}/stand/db/mongo:{{MONGO_DOCKER_TAG}}"

  # human set params
  CLUSTER_PORT: ""


http_proxy:
  # default params
  pipeline: "make_files_and_kuber_no_tests"

  # composed params
  KUBER_IMAGE_TAG: "{{DOCKER_REGISTRY}}/stand/http_proxy"
  PORT: "{{CLUSTER_PORT}}"

  # human set params
  CLUSTER_PORT: ""
  PROXYED_HOST: ""
  PROXYED_PORT: ""