stand_paraphraser_ru:
  CONFIG: paraphraser_rubert
  TEMPLATE: dp
  CLUSTER_PORT: 7003
  MODEL_ARGS: ["text1", "text2"]
  image_polling_timeout_sec: 300
  deployment_polling_timeout_sec: 600
  pipeline: all_up_kuber

stand_ner_ru:
  CONFIG: ner_rus_bert
  TEMPLATE: dp
  CLUSTER_PORT: 7004
  MODEL_ARGS: ["text1"]
  image_polling_timeout_sec: 300
  deployment_polling_timeout_sec: 600
  pipeline: all_up_kuber

stand_ner_en:
  CONFIG: ner_ontonotes_bert_mult
  TEMPLATE: dp
  CLUSTER_PORT: 7010
  MODEL_ARGS: ["text1"]
  image_polling_timeout_sec: 300
  deployment_polling_timeout_sec: 600
  pipeline: all_up_kuber

stand_ner_ml:
  CONFIG: ner_ontonotes_bert_mult
  TEMPLATE: dp
  CLUSTER_PORT: 7013
  MODEL_ARGS: ["text1"]
  image_polling_timeout_sec: 300
  deployment_polling_timeout_sec: 600
  pipeline: all_up_kuber

stand_squad_ru:
  CONFIG: squad_ru_bert_infer
  TEMPLATE: dp
  CLUSTER_PORT: 7005
  MODEL_ARGS: ["text1", "text2"]
  image_polling_timeout_sec: 600
  deployment_polling_timeout_sec: 1200
  pipeline: all_up_kuber

stand_squad_en:
  CONFIG: squad_bert_infer
  TEMPLATE: dp
  CLUSTER_PORT: 7008
  MODEL_ARGS: ["text1", "text2"]
  image_polling_timeout_sec: 600
  deployment_polling_timeout_sec: 1200
  pipeline: all_up_kuber

stand_squad_ml:
  CONFIG: squad_bert_multilingual_freezed_emb
  TEMPLATE: dp
  CLUSTER_PORT: 7014
  MODEL_ARGS: ["text1", "text2"]
  image_polling_timeout_sec: 600
  deployment_polling_timeout_sec: 1200
  pipeline: all_up_kuber

stand_intents_en:
  CONFIG: intents_snips_big
  TEMPLATE: dp
  CLUSTER_PORT: 7007
  MODEL_ARGS: ["text1"]
  image_polling_timeout_sec: 600
  deployment_polling_timeout_sec: 1200
  pipeline: all_up_kuber

stand_ranking_en:
  CONFIG: ranking_insurance_interact
  TEMPLATE: dp
  CLUSTER_PORT: 7009
  MODEL_ARGS: ["text1"]
  image_polling_timeout_sec: 600
  deployment_polling_timeout_sec: 1200
  pipeline: all_up_kuber

stand_insults_en:
  CONFIG: insults_kaggle_conv_bert
  TEMPLATE: dp
  CLUSTER_PORT: 7006
  MODEL_ARGS: ["text1"]
  image_polling_timeout_sec: 600
  deployment_polling_timeout_sec: 1200
  pipeline: all_up_kuber

stand_odqa_en:
  CONFIG: en_odqa_pop_infer_enwiki20180211
  TEMPLATE: dp
  GPU_UNITS_NUM: 1
  CLUSTER_PORT: 7011
  MODEL_ARGS: ["text1"]
  image_polling_timeout_sec: 1200
  deployment_polling_timeout_sec: 2400
  pipeline: all_up_kuber

stand_odqa_ru:
  CONFIG: ru_odqa_infer_wiki_rubert_noans
  TEMPLATE: dp
  BASE_IMAGE: "deeppavlov/base-gpu:0.6.1"
  GPU_UNITS_NUM: 1
  CLUSTER_PORT: 7012
  MODEL_ARGS: ["text1"]
  image_polling_timeout_sec: 600
  deployment_polling_timeout_sec: 1200
  pipeline: all_up_kuber

stand_sentiment_ru:
  CONFIG: rusentiment_elmo_twitter_cnn
  TEMPLATE: dp
  BASE_IMAGE: "deeppavlov/base-gpu:0.6.1"
  CLUSTER_PORT: 7015
  MODEL_ARGS: ["text1"]
  image_polling_timeout_sec: 600
  deployment_polling_timeout_sec: 1200
  pipeline: all_up_kuber

stand_kbqa_ru:
  CONFIG: kbqa_rus
  TEMPLATE: dp
  CLUSTER_PORT: 7016
  MODEL_ARGS: ["text1"]
  image_polling_timeout_sec: 600
  deployment_polling_timeout_sec: 1200
  pipeline: all_up_kuber